spring:
  application:
    name: Payment-App
  datasource:
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8

server:
  port: 8090

mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

